I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script call
    call ch02_main
  File "game/script.rpy", line 7, in script call
    call ch02_main
ScriptError: could not find label 'ch02_main'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script call
    call ch02_main
  File "C:\Users\boa65\Downloads\renpy-6.99.14.3-sdk\renpy\ast.py", line 1384, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 7, in script call
    call ch02_main
  File "C:\Users\boa65\Downloads\renpy-6.99.14.3-sdk\renpy\script.py", line 873, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ch02_main'.

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
re-late 1.0
Mon Apr 23 21:20:34 2018
